----- CREATING A DATABASE FOR MY DSA PROJECT-----

CREATE DATABASE [CAPSTONE PROJECT]
SELECT * FROM [KULTRA MEGA STORES]

--- PRODUCT CATEGORY WITH HIGHEST SALES---
SELECT [PRODUCT CATEGORY], COUNT ([ROW ID]) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
GROUP BY [PRODUCT CATEGORY]
ORDER BY [PRODUCT CATEGORY] DESC

SELECT [PRODUCT CATEGORY], COUNT ( DISTINCT [PRODUCT CATEGORY]) AS [PRODUCT]
FROM [KULTRA MEGA STORES]
GROUP BY [PRODUCT CATEGORY] 
ORDER BY [PRODUCT CATEGORY] DESC

------- THIS GIVES THE TOTAL NUMBER OF SALES INDIVIDUALLY AND NOT THE TOTAL AMOUNT, USING "SUM" GIVES THE AMOUNT-------
SELECT [PRODUCT CATEGORY], COUNT ([SALES]) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
GROUP BY [PRODUCT CATEGORY] 
ORDER BY [TOTAL SALES] DESC

------- FINAL ANSWER TO NUMBER 1 ----
SELECT [PRODUCT CATEGORY], SUM ([SALES]) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
GROUP BY [PRODUCT CATEGORY] 
ORDER BY [TOTAL SALES] DESC
---- TECHNOLOGY HAD THE HIGHEST SALES , ROUNDING 5984248.50----

----QUESTION 2 --
--- TOP 3 AND BOTTOM 3 REGIONS IN TERMS OF SALES---

---- TOP 3 RIGIONS IN TERMS OF SALES--- 
SELECT REGION, SUM ( SALES ) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
GROUP BY REGION
ORDER BY [TOTAL SALES] DESC
------- WEST 1ST POSITION, ONTARIO 2ND POSITION, PRARIE 3RD POSITION---

SELECT TOP 3 REGION, SUM ( SALES ) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
GROUP BY REGION
ORDER BY [TOTAL SALES] DESC

----- BOTTOM 3 REGIONS IN TERMS OF SALES----
SELECT TOP 3 REGION, SUM ( SALES ) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
GROUP BY REGION
ORDER BY [TOTAL SALES] ASC
----- NUNAVUT 1ST POSITION, NORTHWEST TERRITORIES 2ND POSITION, YUKON 3RD POSITION--- 

----- QUESTION 3, SALES OF APPLIANCES IN ONTARIO---

SELECT REGION , COUNT ( [PRODUCT SUB CATEGORY]) AS [TOTAL SLAES]
FROM [KULTRA MEGA STORES]
GROUP BY REGION

SELECT [PRODUCT SUB CATEGORY], COUNT ([SALES]) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
GROUP BY [PRODUCT SUB CATEGORY] 
ORDER BY [TOTAL SALES] DESC



SELECT [PRODUCT SUB CATEGORY], COUNT (SALES) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
WHERE REGION = 'ONTARIO'
GROUP BY [PRODUCT SUB CATEGORY]

---------FINAL ANSWER FOR NUMBER 3-------

SELECT [PRODUCT SUB CATEGORY], SUM (SALES) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
WHERE REGION = 'ONTARIO'
GROUP BY [PRODUCT SUB CATEGORY]
ORDER BY [TOTAL SALES] DESC

----TOTAL SALES FOR APPLIANCES IN ONTARIO IS 202346.84--------- 

SELECT * FROM [KULTRA MEGA STORES]


4----- INCREASING REV FROM BOTTOM 10 CUSTOMERS---

SELECT TOP 10 [CUSTOMER NAME], SUM(SALES) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
GROUP BY [Customer Name]
ORDER BY [TOTAL SALES], [CUSTOMER NAME] ASC


SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Jeremy Farry'

SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Natalie DeCherney'


SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Nicole Fjeld'


SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Katrina Edelman'

SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Dorothy Dickinson'


SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Christine Kargatis'


SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Eric Murdock'

SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Chris McAfee'


SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Rick Huthwaite'


SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Mark Hamilton'


5------MOST EXPENSIVE SHIPPING COST--

------ALL THE KMS LOGISTICS------
SELECT [SHIP MODE], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
GROUP BY [SHIP MODE]
ORDER BY [TOTAL COST]ASC

----INDEPENDENT SHIP COST--
SELECT [SHIP MODE], SUM ([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [SHIP MODE] = 'DELIVERY TRUCK'
GROUP BY [SHIP MODE]
ORDER BY [TOTAL COST]
------- MOST EXPENSIVE DELIVERY SERVICE IS DELIVERY TRUCK WITH COST TOTALING TO 51971.94---

SELECT [SHIP MODE], SUM ([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [SHIP MODE] = 'Regular Air'
GROUP BY [SHIP MODE]
ORDER BY [TOTAL COST]

SELECT [SHIP MODE], SUM ([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [SHIP MODE] = 'EXPRESS Air'
GROUP BY [SHIP MODE]
ORDER BY [TOTAL COST]


6---- MOST VALUABLE CUSTOMERS----

SELECT TOP 10[CUSTOMER NAME],SUM (SALES) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL SALES] DESC


SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Emily Phan'

SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Deborah Brumfield'



SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Roy Skaria'

SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Sylvia Foulston'



SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Grant Carroll'



SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Alejandro Grove'


SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Darren Budd'



SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Julia Barnett'



SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='John Lucas'


SELECT 
     [CUSTOMER NAME],
     [Product Category],
     [CUSTOMER SEGMENT],
     [PRODUCT SUB CATEGORY],
     [ROW ID],
     [Order ID],
     [SHIP MODE],
     [ORDER QUANTITY],
     [SHIPPING COST],
     SALES
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER NAME] ='Liz MacKendrick'

7--- SMALL BUSINESS CUSTOMER WITH HIGHEST SALES--

SELECT [CUSTOMER NAME]
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER SEGMENT] = 'SMALL BUSINESS'
GROUP BY [CUSTOMER NAME]

SELECT TOP 1 [CUSTOMER NAME], SUM (SALES) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER SEGMENT] = 'SMALL BUSINESS'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL SALES] DESC
-----DENNIS KANE HAS HIGHEST SALES WITH 75967.59------

8------CORPORATE CUSTOMER WITH MOST SALES IN 2009-2012-----


SELECT [CUSTOMER NAME], [Order QUANTITY], SUM (SALES) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER SEGMENT] = 'CORPORATE'
GROUP BY [CUSTOMER NAME], [ORDER QUANTITY]
ORDER BY [TOTAL SALES] DESC


SELECT [CUSTOMER NAME], [Order Date], SUM (SALES) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER SEGMENT] = 'CORPORATE'
GROUP BY [CUSTOMER NAME], [ORDER DATE]
ORDER BY [TOTAL SALES] DESC

SELECT [CUSTOMER NAME]
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER SEGMENT] = 'CORPORATE'
GROUP BY [CUSTOMER NAME]

---------ALL ORDERS FROM ALL THE SEGMENTS BETWEEN 2009-01-01 TO 2012-12-31-------
SELECT [CUSTOMER NAME], [CUSTOMER SEGMENT], [ORDER DATE]
FROM [KULTRA MEGA STORES]
WHERE [ORDER DATE] BETWEEN '2009-01-01' AND '2012-12-31' 
ORDER BY [Order Date];


Select * from [KULTRA MEGA STORES]
where [CUSTOMER SEGMENT] = 'CORPORATE' AND [ORDER DATE] >'2009-01-01'


Select [CUSTOMER NAME], COUNT ([ORDER ID]) AS [TOTAL ORDERS]
FROM [KULTRA MEGA STORES]
where [CUSTOMER SEGMENT] = 'CORPORATE' AND [ORDER DATE] >'2009-01-01'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL ORDERS]DESC

Select [CUSTOMER NAME]
FROM [KULTRA MEGA STORES]
where [CUSTOMER SEGMENT] = 'CORPORATE'
GROUP BY [CUSTOMER NAME]

Select * FROM [KULTRA MEGA STORES]
where [CUSTOMER SEGMENT] = 'CORPORATE' AND [ORDER DATE] BETWEEN '2009-01-01' AND '2012-01-01' 


Select * FROM [KULTRA MEGA STORES]
where [CUSTOMER SEGMENT] = 'CORPORATE' AND [ORDER DATE] BETWEEN '2009-01-01' AND '2012-01-01' 


Select [CUSTOMER NAME], COUNT ([ORDER ID]) AS [TOTAL ORDERS]
FROM [KULTRA MEGA STORES]
where [CUSTOMER SEGMENT] = 'CORPORATE' AND [ORDER DATE] BETWEEN '2009' AND '2012'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL ORDERS]DESC

SELECT * FROM [KULTRA MEGA STORES]


Select [CUSTOMER NAME], COUNT ([ORDER QUANTITY]) AS [TOTAL ORDERS]
FROM [KULTRA MEGA STORES]
where [CUSTOMER SEGMENT] = 'CORPORATE' AND [ORDER DATE] BETWEEN '2009' AND '2012'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL ORDERS]DESC

SELECT [CUSTOMER SEGMENT], COUNT([ORDER QUANTITY]) AS [TOTAL QUANTITY]
FROM [KULTRA MEGA STORES]
GROUP BY [CUSTOMER SEGMENT]
ORDER BY [TOTAL QUANTITY]ASC


SELECT [CUSTOMER SEGMENT], COUNT(DISTINCT[CUSTOMER NAME]) AS CUSTOMER
FROM [KULTRA MEGA STORES]
GROUP BY [CUSTOMER SEGMENT]
ORDER BY CUSTOMER ASC

9------most pofitable consumer customer-------

SELECT * FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER SEGMENT] ='CONSUMER' and [CUSTOMER NAME] = 'EMILY PHAN'


SELECT [CUSTOMER NAME], SUM (SALES) AS [TOTAL SALES]
FROM [KULTRA MEGA STORES]
WHERE [CUSTOMER SEGMENT] = 'CONSUMER'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL SALES] DESC

10----- RETURNED ITEMS------

SELECT * FROM [KULTRA MEGA STORES]

THERE IS NO COLUMN FOR RETURNED ITEMS IN THE TABLE, NO COLUMN FOR COMPLAINS

11----If the delivery truck is the most economical but the slowest shipping method and
--Express Air is the fastest but the most expensive one, do you think the company
---appropriately spent shipping costs based on the Order Priority? Explain your answer

----ORDER_PRIORITY LIST 
       ---Medium
        --Not Specified
        ---Critical
         ---High
          ---Low

------ALL THE KMS LOGISTICS------
SELECT [SHIP MODE], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
GROUP BY [Ship Mode]
ORDER BY [TOTAL Cost]ASC

SELECT [SHIP MODE], COUNT([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
GROUP BY [Ship Mode]
ORDER BY [TOTAL Cost]ASC

SELECT  [Order Priority], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
GROUP BY [Order Priority]
ORDER BY [TOTAL Cost]ASC

SELECT [Order Priority], [SHIP MODE], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
GROUP BY [Order Priority],[Ship Mode]
ORDER BY [TOTAL Cost]ASC

SELECT [CUSTOMER NAME], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'HIGH' AND  [SHIP MODE] = 'EXPRESS AIR'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL COST] DESC



SELECT [CUSTOMER NAME], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'MEDIUM' AND  [SHIP MODE] = 'EXPRESS AIR'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL COST] DESC


SELECT [CUSTOMER NAME], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'LOW' AND  [SHIP MODE] = 'EXPRESS AIR'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL COST] DESC


SELECT [CUSTOMER NAME], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'CRITICAL' AND  [SHIP MODE] = 'EXPRESS AIR'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL COST] DESC


SELECT [CUSTOMER NAME], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'NOT SPECIFIED' AND  [SHIP MODE]= 'EXPRESS AIR'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL COST] DESC




SELECT [CUSTOMER NAME], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'HIGH' AND  [SHIP MODE]= 'REGULAR AIR'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL COST] DESC



SELECT [CUSTOMER NAME], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'MEDIUM' AND  [SHIP MODE]= 'REGULAR AIR'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL COST] DESC




SELECT [CUSTOMER NAME], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'LOW' AND  [SHIP MODE]= 'REGULAR AIR'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL COST] DESC




SELECT [CUSTOMER NAME], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'CRITICAL' AND  [SHIP MODE]= 'REGULAR AIR'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL COST] DESC



SELECT [CUSTOMER NAME], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'NOT SPECIFIED' AND  [SHIP MODE]= 'REGULAR AIR'
GROUP BY [CUSTOMER NAME]
ORDER BY [TOTAL COST] DESC




SELECT [Order Priority], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'HIGH' AND  [SHIP MODE] = 'DELIVERY TRUCK'
GROUP BY [Order Priority]
ORDER BY [TOTAL COST] DESC



SELECT [Order Priority], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'LOW' AND  [SHIP MODE] = 'DELIVERY TRUCK'
GROUP BY [Order Priority]
ORDER BY [TOTAL COST] DESC



SELECT [Order Priority], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'CRITICAL' AND  [SHIP MODE] = 'DELIVERY TRUCK'
GROUP BY [Order Priority]
ORDER BY [TOTAL COST] DESC


SELECT [Order Priority], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'MEDIUM' AND  [SHIP MODE] = 'DELIVERY TRUCK'
GROUP BY [Order Priority]
ORDER BY [TOTAL COST] DESC


SELECT [Order Priority], SUM([SHIPPING COST]) AS [TOTAL COST]
FROM [KULTRA MEGA STORES]
WHERE [Order Priority] = 'NOT SPECIFIED' AND  [SHIP MODE] = 'DELIVERY TRUCK'
GROUP BY [Order Priority]
ORDER BY [TOTAL COST] DESC
















